const textures = {
    strikers: {
        uiName: {
            en: 'Striker',
            uk: 'Біток',
        },
        materialName: "mat_striker_pattern",
        stiker_0: {
            uiImage: '/textures/striker/striker_0.png',
            map: '/textures/striker/striker_0.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_1: {
            uiImage: '/textures/striker/striker_1.png',
            map: '/textures/striker/striker_1.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_2: {
            uiImage: '/textures/striker/striker_2.png',
            map: '/textures/striker/striker_2.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_3: {
            uiImage: '/textures/striker/striker_3.png',
            map: '/textures/striker/striker_3.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_4: {
            uiImage: '/textures/striker/striker_4.png',
            map: '/textures/striker/striker_4.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_5: {
            uiImage: '/textures/striker/striker_5.png',
            map: '/textures/striker/striker_5.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_6: {
            uiImage: '/textures/striker/striker_6.png',
            map: '/textures/striker/striker_6.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_7: {
            uiImage: '/textures/striker/striker_7.png',
            map: '/textures/striker/striker_7.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_8: {
            uiImage: '/textures/striker/striker_8.png',
            map: '/textures/striker/striker_8.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_9: {
            uiImage: '/textures/striker/striker_9.png',
            map: '/textures/striker/striker_9.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        stiker_10: {
            uiImage: '/textures/striker/striker_10.png',
            map: '/textures/striker/striker_10.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.105,
            roughness: 0.135,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    coins: {
        uiName: {
            en: 'Coin color set',
            uk: 'Колір фішок',
        },
        materialName: "mat_carrom_piece",
        blackWhite: {
            uiImage: '/textures/coins/blackWhite.png',
            uiName: {
                en: 'Black and White',
                uk: 'Чорно-білі',
            },
            nameInGame: {
                white: { en: 'White', uk: 'Білий' },
                black: { en: 'Black', uk: 'Чорний' },
            },
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            colorWhite: 0xaaaaaa,
            colorBlack: 0x1a1a1a,
            colorRed: 0x9E0500,
            metalness: 0.0,
            roughness: 0.238,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        beigeBrown: {
            uiImage: '/textures/coins/beigeBrown.png',
            uiName: {
                en: 'Beige and Brown',
                uk: 'Бежеві та коричневі',
            },
            nameInGame: {
                white: { en: 'Beige', uk: 'Бежевий' },
                black: { en: 'Brown', uk: 'Коричневий' },
            },
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            colorWhite: 0xeeaa66,
            colorBlack: 0x553311,
            colorRed: 0x9E0500,
            metalness: 0.0,
            roughness: 0.238,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        goldSilver: {
            uiImage: '/textures/coins/goldSilver.png',
            uiName: {
                en: 'Gold and Silver',
                uk: 'Золоті та срібні',
            },
            nameInGame: {
                white: { en: 'Gold', uk: 'Золотий' },
                black: { en: 'Silver', uk: 'Срібний' },
            },
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            colorWhite: 0xffd700,
            colorBlack: 0xc0c0c0,
            colorRed: 0x9E0500,
            metalness: 1,
            roughness: 0.1,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    pocketCorners: {
        uiName: {
            en: 'Pocket corners',
            uk: 'Кути лунок',
        },
        materialName: "mat_frame_corners",
        sameAsFrame: {
            uiImage: '/textures/pocketCorners/sameAsFrame.png',
            uiName: { en: 'Same as frame', uk: 'Як на бортах', },
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            metalness: 0,
            roughness: null,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        gold: {
            uiImage: '/textures/pocketCorners/gold.png',
            uiName: { en: 'Golden', uk: 'Золоті', },
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: 0xb28d42,
            metalness: 0.905,
            roughness: 0.071,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        silver: {
            uiImage: '/textures/pocketCorners/silver.png',
            uiName: {en: 'Silver', uk: 'Срібні',},
            map: null,
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: 0xc0c0c0,
            metalness: 0.905,
            roughness: 0.071,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        darkWood: {
            uiImage: '/textures/frame/boardSides/Dark_Stained.jpg',
            uiName: {en: 'Dark Wood', uk: 'Темне дерево',},
            map: '/textures/frame/boardSides/Dark_Stained.jpg',
            normalMap: '/textures/frame/boardSides/oak_normal.png',
            roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
            metalnessMap: null,
            color: null,
            metalness: null,
            roughness: null,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        lightWood: {
            uiImage: '/textures/frame/boardSides/Naturel.jpg',
            uiName: {en: 'Light Wood', uk: 'Світле дерево',},
            map: '/textures/frame/boardSides/Naturel.jpg',
            normalMap: '/textures/frame/boardSides/oak_normal.png',
            roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
            metalnessMap: null,
            color: null,
            metalness: 0,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    boardSurface: {
        uiName: {en: 'Surface Material', uk: 'Матеріал поверхні',},
        materialName: "mat_board_top",
        plywood_0: {
            uiImage: '/textures/board/surface/plywood.jpg',
            map: '/textures/board/surface/plywood.jpg',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.00,
            roughness: 0.45,
            repeatX: 2,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        plywood_1: {
            uiImage: '/textures/board/surface/plywood2.jpg',
            map: '/textures/board/surface/plywood2.jpg',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.00,
            roughness: 0.45,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        marble_0: {
            uiImage: '/textures/board/surface/marble.jpg',
            map: '/textures/board/surface/marble.jpg',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.10,
            roughness: 0.10,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        marble_1: {
            uiImage: '/textures/board/surface/marble2.jpg',
            map: '/textures/board/surface/marble2.jpg',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.10,
            roughness: 0.10,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        marble_2: {
            uiImage: '/textures/board/surface/marble3.jpg',
            map: '/textures/board/surface/marble3.jpg',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.10,
            roughness: 0.10,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    boardPattern: {
        uiName: { en: 'Surface Pattern', uk: 'Малюнок поверхні', },
        materialName: "mat_board_pattern",
        armenia: {
            uiImage: '/textures/board/pattern/armenia.png',
            map: '/textures/board/pattern/armenia.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        bali: {
            uiImage: '/textures/board/pattern/bali.png',
            map: '/textures/board/pattern/bali.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        classic: {
            uiImage: '/textures/board/pattern/classic.png',
            map: '/textures/board/pattern/classic.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        crete: {
            uiImage: '/textures/board/pattern/crete.png',
            map: '/textures/board/pattern/crete.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        india: {
            uiImage: '/textures/board/pattern/india.png',
            map: '/textures/board/pattern/india.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        pakistan: {
            uiImage: '/textures/board/pattern/pakistan.png',
            map: '/textures/board/pattern/pakistan.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        persia: {
            uiImage: '/textures/board/pattern/persia.png',
            map: '/textures/board/pattern/persia.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        simple: {
            uiImage: '/textures/board/pattern/simple.png',
            map: '/textures/board/pattern/simple.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        turkey: {
            uiImage: '/textures/board/pattern/turkey.png',
            map: '/textures/board/pattern/turkey.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        ukraine: {
            uiImage: '/textures/board/pattern/ukraine.png',
            map: '/textures/board/pattern/ukraine.png',
            uiName: { en: null, uk: null, },
            normalMap: null,
            roughnessMap: null,
            metalnessMap: null,
            color: null,
            metalness: 0.7,
            roughness: 0.3,
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    frames: {
        uiName: { en: 'Frame Texture', uk: 'Текстура бортів', },
        materialName: "mat_frame_wood",
        dark_Stained: {
            uiImage: '/textures/frame/boardSides/Dark_Stained.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Dark_Stained.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        leem: {
            uiImage: '/textures/frame/boardSides/Leem.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Leem.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        naturel: {
            uiImage: '/textures/frame/boardSides/Naturel.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Naturel.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        noten: {
            uiImage: '/textures/frame/boardSides/Noten.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Noten.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        noten_elite: {
            uiImage: '/textures/frame/boardSides/Noten_mat.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Noten_mat.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/Noten_mat_normal.png',
                    roughnessMap: '/textures/frame/boardSides/Noten_mat_roughness.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/Noten_gloss_roughness.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        rock: {
            uiImage: '/textures/frame/boardSides/Rock.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Rock.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        royal_grey: {
            uiImage: '/textures/frame/boardSides/Royal_Grey.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Royal_Grey.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        tabacco: {
            uiImage: '/textures/frame/boardSides/Tabacco.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Tabacco.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        tabacco_white: {
            uiImage: '/textures/frame/boardSides/Tabacco_White.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Tabacco_White.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
        tabacco_black: {
            uiImage: '/textures/frame/boardSides/Tabacco_Zwart.jpg',
            uiName: { en: null, uk: null, },
            map: '/textures/frame/boardSides/Tabacco_Zwart.jpg',
            finishType: {
                matte: {
                    normalMap: '/textures/frame/boardSides/oak_normal.png',
                    roughnessMap: '/textures/frame/boardSides/oak_rough.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
                glossy: {
                    normalMap: null,
                    roughnessMap: '/textures/frame/boardSides/oak_rough_gloss.jpg',
                    metalnessMap: null,
                    color: null,
                    metalness: null,
                    roughness: null,
                },
            },
            repeatX: 1,
            repeatY: 1,
            offset: { x: 0, y: 0 },
            flipX: false,
            flipY: false,
            rotation: 0,
        },
    },
    environments: {
        uiName: { en: 'Environment', uk: 'Оточення', },
        neutral: {
            uiImage: null,
            file: '/environment/neutral.hdr',
            uiName: { en: 'Neutral Studio', uk: 'Нейтральна студія', },
        },
        studio: {
            uiImage: null,
            file: '/environment/brown_photostudio_07_1k.hdr',
            uiName: { en: 'Brown Studio', uk: 'Коричнева студія', },
        },
    },
};

export default textures;
